package ui;

import java.awt.GraphicsEnvironment;
import trabalhoia.Jogador;
import trabalhoia.Settings;

/**
 *
 * @author pedronote
 */
public class OpcoesGerais extends javax.swing.JFrame {

    private int tipoGame;
    private Settings configuracaoInicial;
    
    public OpcoesGerais(int tipoGame) {
        this.tipoGame = tipoGame;
        initComponents();
        myInits();
    }

    private void myInits(){
        setResizable(false);
        setLocationRelativeTo(null);
        setSize(330, 180);
       
        configuracaoInicial = new Settings(tipoGame);
    }
    
    private void criaJogadores(){
        configuracaoInicial.jogador1 = new Jogador();
        configuracaoInicial.jogador1.dinheiroTotal = configuracaoInicial.investimentoInicial;
        configuracaoInicial.jogador1.id = 1;
        configuracaoInicial.jogador2 = new Jogador();
        configuracaoInicial.jogador2.dinheiroTotal = configuracaoInicial.investimentoInicial;
        configuracaoInicial.jogador2.id = 2;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputMeses = new javax.swing.JSpinner();
        inputInvestimentoInicial = new javax.swing.JComboBox<>();
        inputRamo = new javax.swing.JComboBox<>();
        btnComecar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurações Gerais");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Meses:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Investimento Inicial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.insets = new java.awt.Insets(8, 16, 8, 16);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Ramo do Negócio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.insets = new java.awt.Insets(8, 16, 8, 16);
        getContentPane().add(jLabel3, gridBagConstraints);

        inputMeses.setModel(new javax.swing.SpinnerNumberModel(12, 12, 36, 1));
        inputMeses.setToolTipText("Meses até final do jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        getContentPane().add(inputMeses, gridBagConstraints);

        inputInvestimentoInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50000", "100000", "500000" }));
        inputInvestimentoInicial.setToolTipText("Dinheiro inicial para cada empresa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
        getContentPane().add(inputInvestimentoInicial, gridBagConstraints);

        inputRamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia" }));
        inputRamo.setToolTipText("Ramo compartilhado pelas empresas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
        getContentPane().add(inputRamo, gridBagConstraints);

        btnComecar.setText("Começar");
        btnComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComecarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 2, 1);
        getContentPane().add(btnComecar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComecarActionPerformed
        int mesesMaximo = (Integer) inputMeses.getValue();
        configuracaoInicial.maximoMeses = mesesMaximo;
        
        int investimentoSelecionado = inputInvestimentoInicial.getSelectedIndex();
        double investimentoInicial = Double.valueOf(inputInvestimentoInicial.getItemAt(investimentoSelecionado));
        configuracaoInicial.investimentoInicial = investimentoInicial;
        
        int ramoSelecionado = inputRamo.getSelectedIndex();
        String ramoNegocio = inputRamo.getItemAt(ramoSelecionado);
        configuracaoInicial.negocio = MenuWindow.getBancoDeDados().getNegocioByNome(ramoNegocio);
        
        criaJogadores(); 
        dispose();
        new JanelaJogo(configuracaoInicial).setVisible(true);
    }//GEN-LAST:event_btnComecarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComecar;
    private javax.swing.JComboBox<String> inputInvestimentoInicial;
    private javax.swing.JSpinner inputMeses;
    private javax.swing.JComboBox<String> inputRamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
