/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Dimension;

/**
 *
 * @author Pedro
 */
public class InstruWindow extends javax.swing.JFrame {
    
    public InstruWindow() {
        initComponents();
        myInits();
    }
    
    private void myInits(){
        setPreferredSize(new Dimension(MenuWindow.WINDOW_WIDTH, MenuWindow.WINDOW_HEIGHT));
        setResizable(false);
        setLocationRelativeTo(null);
        txtInstrucoes.setLineWrap(true);
        txtInstrucoes.setWrapStyleWord(true);
        txtInstrucoes.setEditable(false);
        if (MenuWindow.debugMode)
            System.out.println("Abriu Instruções");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInstrucoes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instruções - Company Wars");
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(800, 600));

        btnVoltar.setText("Voltar para Menu");
        btnVoltar.setPreferredSize(new java.awt.Dimension(150, 35));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Instruções");

        txtInstrucoes.setBackground(new java.awt.Color(240, 240, 240));
        txtInstrucoes.setColumns(20);
        txtInstrucoes.setRows(5);
        txtInstrucoes.setText("1 - Escolha o modo de jogo no menu principal.\n\n2 - Defina os valores iniciais dos jogadores para começar o jogo.\n\n2.1 - Variáveis\nValor Inicial de Investimento: \n    Qual o valor inicial que o jogador deseja investir para começar o primeiro mês de jogo. Formato do campo: 99,99\nPrédio: \n    Prédio 1 - Custo: 100MIL R$ | 10 produtos/mês\n    Prédio 2 - Custo: 200MIL R$ | 20 produtos/mês\n    Prédio 3 - Custo: 300MIL R$ | 30 produtos/mês \nProduto:\n   Nome do produto a ser fabricado.\nPreço do Produto:\n    Preço da unidade do produto. Formato do campo: 99,99\nTempo de Fabricação:\n    Tempo de fabricação de cada unidade do produto. Tempo em Semanas\nPreço de Insumos:\n    Preço da matéria prima para fabricação de cada unidade do produto. Formato do campo: 99,99\nGasto com Propaganda:\n    Gasto inicial em propaganda. Formato do campo: 99,99\nGastos Fixos:\n    Gastos fixos como energia, água, telefone, internet. Formato do campo: 99,99\nTempo Total do Jogo:\n    Tempo total de duração do jogo em meses. Tempo em Meses\n\n3 - Uma rodada acontece em 3 turnos, o turno do Jogador 1, turno do Jogador 2 e o turno do Sistema. Cada rodada completa corresponde a 1 mês no tempo do jogo. O jogo acaba quando o máximo de rodadas é atingido e o vencedor é o jogador com mais lucro no último mês.\n");
        txtInstrucoes.setToolTipText("");
        jScrollPane1.setViewportView(txtInstrucoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel1)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
        new MenuWindow().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtInstrucoes;
    // End of variables declaration//GEN-END:variables
}
